# Generated by Django 4.1.2 on 2023-03-14 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_credential', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255, null=True)),
                ('companyaddress', models.CharField(max_length=255, null=True)),
                ('phonenumber', models.IntegerField(default='-', null=True)),
                ('companystatus', models.CharField(max_length=255, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankname', models.CharField(max_length=255, null=True)),
                ('fueltype', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=255)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.company')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pumpname', models.CharField(max_length=255, null=True)),
                ('islandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.island')),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzlename', models.CharField(max_length=255, null=True)),
                ('fueltype', models.CharField(max_length=255, null=True)),
                ('pumpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.pump')),
                ('tankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.tank')),
            ],
        ),
        migrations.CreateModel(
            name='Meters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metername', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('tankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.tank')),
            ],
        ),
        migrations.AddField(
            model_name='island',
            name='stationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.station'),
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_volume', models.CharField(max_length=255, null=True)),
                ('meterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_credential.meters')),
            ],
        ),
    ]
