# Generated by Django 3.2 on 2023-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_credential', '0005_auto_20230324_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('companyname', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
