# Generated by Django 3.2 on 2023-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_credential', '0006_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='technicianname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nozzle',
            name='technicianname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='technicianname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='technicianname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
