# Generated by Django 3.2 on 2023-03-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_credential', '0007_auto_20230324_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='island',
            name='technicianname',
        ),
        migrations.RemoveField(
            model_name='nozzle',
            name='technicianname',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='technicianname',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='technicianname',
        ),
        migrations.AddField(
            model_name='island',
            name='technicianid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sub_credential.technician'),
        ),
        migrations.AddField(
            model_name='nozzle',
            name='technicianid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sub_credential.technician'),
        ),
        migrations.AddField(
            model_name='pump',
            name='technicianid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sub_credential.technician'),
        ),
        migrations.AddField(
            model_name='tank',
            name='technicianid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sub_credential.technician'),
        ),
    ]
