# Generated by Django 3.2 on 2023-03-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_credential', '0008_auto_20230324_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='island',
            new_name='iland',
        ),
        migrations.RenameField(
            model_name='iland',
            old_name='islandname',
            new_name='ilandname',
        ),
        migrations.RenameField(
            model_name='pump',
            old_name='islandid',
            new_name='ilandid',
        ),
    ]
