# Generated by Django 3.2 on 2023-03-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_credential', '0009_auto_20230325_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iland',
            name='technicianid',
        ),
        migrations.RemoveField(
            model_name='nozzle',
            name='technicianid',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='technicianid',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='technicianid',
        ),
    ]
