# Generated by Django 3.2 on 2023-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_credential', '0004_auto_20230321_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='userid',
            new_name='usertype',
        ),
        migrations.AddField(
            model_name='company',
            name='companyrotation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='companystaff',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='companystation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stationmanagers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Systemadmin',
        ),
    ]
